[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.19.1",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "librosa>=0.11.0",
    "openai>=3.8.0",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
    "yt-dlp>=2026.8.19",
]
