"""add transcript and prosody fields

Revision ID: f618ed664d1c
Revises: 51d844d6e793
Create Date: 2026-09-05 11:24:48.908064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f618ed664d1c'
down_revision: Union[str, Sequence[str], None] = '51d844d6e793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('transcript_json', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('speech_ratio', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('avg_pause_length_sec', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('avg_pitch_variation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'avg_pitch_variation')
    op.drop_column('videos', 'avg_pause_length_sec')
    op.drop_column('videos', 'speech_ratio')
    op.drop_column('videos', 'transcript_json')
    # ### end Alembic commands ###
